Vinyoxla.MVC/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Vinyoxla.MVC.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Vinyoxla.MVC/Controllers/ImageController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Vinyoxla.MVC.Controllers
{
    public class ImageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Vinyoxla.MVC/Controllers/PurchaseController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Threading.Tasks;
using Vinyoxla.Service.Interfaces;
using Vinyoxla.Service.ViewModels.BankVMs;
using Vinyoxla.Service.ViewModels.PurchaseVMs;

namespace Vinyoxla.MVC.Controllers
{
    public class PurchaseController : Controller
    {
        private readonly IPurchaseService _purchaseService;

        public PurchaseController(IPurchaseService purchaseService)
        {
            _purchaseService = purchaseService;
        }

        public async Task<IActionResult> PrePurchase(SelectedReportVM selectedReportVM)
        {
            if (User.Identity.IsAuthenticated)
            {
                string phone = await _purchaseService.GetUserPhoneNumber();
                int userBalance = await _purchaseService.GetUserBalance();

                string result = await _purchaseService.CheckEverything(phone, selectedReportVM.Vin, false);

                if (result == "0")
                {
                    return RedirectToAction("Error", new { errno = 0 });
                }
                else if (result == "1")
                {
                    if (userBalance >= 4)
                    {
                        await _purchaseService.SubstractFromBalance();

                        string fileName = await _purchaseService.ReplaceOldReport(phone, selectedReportVM.Vin, true, "balance", "balance");

                        if (fileName == null)
                        {
                            return RedirectToAction("Error", new { errno = 1 });
                        }

                        return RedirectToAction("Index", "Report", new { fileName });
                    }
                    else
                    {
                        return View(await _purchaseService.GetViewModelForOrderPage(selectedReportVM));
                    }
                }
                else if (result == "2")
                {
                    if (userBalance >= 4)
                    {
                        await _purchaseService.SubstractFromBalance();

                        string fileName = await _purchaseService.GetReport(phone, selectedReportVM.Vin, true, "balance", "balance");

                        if (fileName == null)
                        {
                            return RedirectToAction("Error", new { errno = 2 });
                        }

                        return RedirectToAction("Index", "Report", new { fileName });
                    }
                    else
                    {
                        return View(await _purchaseService.GetViewModelForOrderPage(selectedReportVM));
                    }
                }

                return RedirectToAction("Index", "Report", new { fileName = result });
            }
            else
            {
                return View(await _purchaseService.GetViewModelForOrderPage(selectedReportVM));
            }
        }

        [HttpPost]
        public async Task<IActionResult> Purchase(OrderVM orderVM)
        {
            string url = await _purchaseService.Bank(orderVM.Vin, orderVM.PhoneNumber);

            if (url != null)
            {
                return RedirectPermanent(url);
            }

            return RedirectToAction("Error", new { errno = 3 });
        }

        public async Task<IActionResult> GetReport()
        {
            string cookieInfo = HttpContext.Request.Cookies["cookieInfo"];

            CookieInfoVM cookieInfoVM = new CookieInfoVM();

            if (string.IsNullOrWhiteSpace(cookieInfo))
            {
                return RedirectToAction("Index", "Home");
            }

            cookieInfoVM = JsonConvert.DeserializeObject<CookieInfoVM>(cookieInfo);

            string orderId = cookieInfoVM.OrderId;
            string sessionId = cookieInfoVM.SessionId;
            string phoneno = cookieInfoVM.PhoneNumber;
            string vin = cookieInfoVM.VinCode;

            HttpContext.Response.Cookies.Delete("cookieInfo");

            if (await _purchaseService.CheckOrder(orderId, sessionId, phoneno, vin))
            {
                if (User.Identity.IsAuthenticated)
                {
                    string fileName = await _purchaseService.GetReport(phoneno, vin, false, orderId, sessionId);

                    if (fileName == null)
                    {
                        return RedirectToAction("Error", new { errno = 2 });
                    }

                    return RedirectToAction("Index", "Report", new { fileName });
                }
                else
                {
                    string result = await _purchaseService.CheckEverything(phoneno, vin, true);

                    if (result == "0")
                    {
                        return RedirectToAction("Error", new { errno = 0 });
                    }
                    else if (result == "1")
                    {
                        string fileName = await _purchaseService.ReplaceOldReport(phoneno, vin, false, orderId, sessionId);

                        if (fileName == null)
                        {
                            return RedirectToAction("Error", new { errno = 1 });
                        }

                        return RedirectToAction("Index", "Report", new { fileName });
                    }
                    else if (result == "2")
                    {
                        string fileName = await _purchaseService.GetReport(phoneno, vin, false, orderId, sessionId);

                        if (fileName == null)
                        {
                            return RedirectToAction("Error", new { errno = 2 });
                        }

                        return RedirectToAction("Index", "Report", new { fileName });
                    }

                    return RedirectToAction("Index", "Report", new { fileName = result });
                }
            }
            else
            {
                return RedirectToAction("Error", new { errno = 10 });
            }
        }

        public async Task<IActionResult> Error(int errno)
        {
            return View(errno);
        }
    }
}

//rusum az esli elektrik < 3 let, idxal = 0

Vinyoxla.MVC/Views/Shared/_AccountCodePartial.cshtml
@model LoginVM

<label for="code" class="col-lg-12 col-12">Göndərilən kod:</label>
<div class="inputkeeper col-lg-12 col-12">
    <input asp-for="Code" inputmode="numeric" autocomplete="Code" placeholder="1234" type="text"
           maxlength="4" minlength="4" class="code col-lg-12 col-12" id="code">
</div>

Vinyoxla.MVC/Views/Shared/_CarfaxResultPartial.cshtml
@model CarfaxVM

<form method="post" enctype="multipart/form-data" asp-controller="Purchase" asp-action="PrePurchase" class="col-lg-12 col-12 icindeki">
    <div class="col-lg-12 col-12 top">
        <div class="toptop col-lg-12 col-12">
            <span class="col-lg-8 col-8 topelement">
                <span class="col-lg-2 col-12">Model:</span>
                <span class="col-lg-10 col-12" id="autoNameCarfax">@Model.Vehicle</span>
                <input class="d-none" asp-for="Vehicle" />
            </span>
            <span class="col-lg-4 col-4 topelement">
                <span class="col-12 col-lg-8">Buraxılış ili:</span>
                <span class="col-12 col-lg-4" id="yearCarfax">@Model.Year</span>
                <input class="d-none" asp-for="Year" />
            </span>
        </div>
        <div class="topbottom col-lg-12 col-12">
            <span class="col-lg-8 col-8 topelement">
                <span class="col-lg-2 col-12">VIN:</span>
                <span class="col-lg-10 col-11" id="vinCodeCarfax">@Model.Vin</span>
                <input class="d-none" asp-for="Vin" />
            </span>
            <span class="col-lg-4 col-4 topelement">
                <span class="col-12 col-lg-8">Məlumat sayı:</span>
                <span class="col-12 col-lg-4" id="recordsCountCarfax">@Model.Records</span>
                <input class="d-none" asp-for="Records" />
            </span>
        </div>
    </div>

    <div class="col-lg-12 col-12 bottom">
        <div class="col-lg-3 col-3-5">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 378.51 70.97">
                <defs>
                    <style>
                        .cls-1,
                        .cls-3 {
                            fill: #fff;
                        }

                        .cls-1 {
                            fill-rule: evenodd;
                        }

                        .cls-2 {
                            fill: #231f20;
                        }
                    </style>
                </defs>
                <g id="Layer_2" data-name="Layer 2">
                    <g id="Layer_1-2" data-name="Layer 1">
                        <path d="M364.08 64a5.51 5.51 0 0 1-5.58 5.44H7.1A5.51 5.51 0 0 1 1.52 64V7A5.52 5.52 0 0 1 7.1 1.52h351.4A5.52 5.52 0 0 1 364.08 7z"
                              class="cls-1" />
                        <path d="M358.5 71H7.1A7 7 0 0 1 0 64V7a7 7 0 0 1 7.1-7h351.4a7 7 0 0 1 7.1 7v57a7 7 0 0 1-7.1 7zM7.1 3A4 4 0 0 0 3 7v57a4 4 0 0 0 4.1 3.94h351.4a4 4 0 0 0 4.06-3.94V7a4 4 0 0 0-4.06-4z"
                              class="cls-2" />
                        <path d="M303.72 6.55H358.89000000000004V64.26H303.72z" class="cls-3" />
                        <path d="M65.59 5.87H122.28V65.1H65.59z" class="cls-2" />
                        <path d="M124.74 5.87H181.43V65.1H124.74z" class="cls-2" />
                        <path d="M184.28 5.87H240.97V65.1H184.28z" class="cls-2" />
                        <path d="M243.82 5.87H300.51V65.1H243.82z" class="cls-2" />
                        <path d="M6.06 5.87H62.75V65.1H6.06z" class="cls-2" />
                        <path d="M35.71 56.28c-11.76 0-18-8.69-18-20.42 0-12.75 7.46-20.42 18.08-20.42 9.73 0 13.57 4.18 16.28 11.64L42.09 31c-1.41-3.69-2.77-6-6.38-6-4.59 0-6.57 4.59-6.57 10.88 0 6.06 1.92 10.88 6.68 10.88 3.44 0 4.92-1.87 7.06-5.61l9.27 4.94c-2.65 5.16-7.06 10.19-16.44 10.19zM97.37 39.53h-6.56l.73-2.6c1.42-5 2-7.22 2.55-9.88.51 2.66 1.13 4.8 2.54 9.88zM114 55.21 99.68 15.64H88.6L74.24 55.21H86l2.15-7H100l2.15 7zM158.63 29c0 2.84-1.41 4.42-5 4.42h-6.43v-8.67h6.62c3.45 0 4.81 1.77 4.81 4.25zm11.71 26.4-7.92-15.11c4.35-2 7.13-5.63 7.13-11.57 0-9.39-6.17-12.89-15.45-12.89h-17.7V55.4h10.8V42h4.41l6.46 13.36zM207.85 25.14v5.52h12.38v9.26h-12.38V55.4h-10.91V15.83h31.32v9.31zM275 39.84h-6.56l.74-2.59c1.41-5 2-7.23 2.54-9.89.51 2.66 1.13 4.8 2.55 9.89zm16.68 15.68L277.36 16h-11.08l-14.36 39.52h11.76l2.15-7h11.87l2.15 7z"
                              class="cls-3" />
                        <path d="M303 5.79V65h56.69V5.79zm22.75 57.71 1-1.38a68.74 68.74 0 0 0 4.25-7.26c1.05 2.14 2.6 4.79 4.15 7.26l.85 1.38zm32.38 0h-8.45l-11.92-17 13.67-19.2h-13.61l-2.41 3.83a80.72 80.72 0 0 0-4.21 7.2 67.07 67.07 0 0 0-4.15-7.2l-2.41-3.83h-13.92l13.67 19.46-12.08 16.74h-7.82V7.32h53.64z"
                              class="cls-2" />
                        <path d="M377 1.73a5 5 0 0 0-3.73-1.57 5 5 0 0 0-3.74 1.57A5.29 5.29 0 0 0 368 5.56a5.16 5.16 0 0 0 1.55 3.78 5.08 5.08 0 0 0 3.73 1.56A5 5 0 0 0 377 9.33a5.22 5.22 0 0 0 1.53-3.79A5.25 5.25 0 0 0 377 1.73zm-.76 7-1.89-2.53a2.25 2.25 0 0 0 1.27-.53 1.83 1.83 0 0 0 .65-1.46 1.81 1.81 0 0 0-.57-1.37 2.33 2.33 0 0 0-1.7-.58h-3.15v6.43H372V6.18h.93l1.89 2.51h1.39a4 4 0 0 1-3 1.28 4.08 4.08 0 0 1-3-1.3A4.28 4.28 0 0 1 369 5.56a4.37 4.37 0 0 1 1.26-3.13 4.1 4.1 0 0 1 3.06-1.31 3.93 3.93 0 0 1 2.93 1.31 4.39 4.39 0 0 1 1.26 3.11 4.36 4.36 0 0 1-1.26 3.12zm-1.13-4.53c0 .67-.42 1-1.28 1H372V3.31h1.73c.92 0 1.36.28 1.36.85z"
                              class="cls-3" />
                    </g>
                </g>
            </svg>
        </div>
        <span class="price">4 ₼</span>
        <button type="submit">Almaq</button>
    </div>
</form>

Vinyoxla.MVC/Views/Shared/_ImageResultPartial.cshtml
@model ImageVM

<form method="post" enctype="multipart/form-data" asp-controller="Image" asp-action="Index" class="col-lg-12 col-12 icindeki">
    <div class="col-lg-12 col-12 top">
        <div class="toptop col-lg-12 col-12">
            <span class="col-lg-8 col-8 topelement">
                <span class="col-lg-2 col-12">Model:</span>
                <span class="col-lg-10 col-12" id="autoNameImage">@Model.Vehicle</span>
            </span>
            <span class="col-lg-4 col-4 topelement">
                <span class="col-12 col-lg-8">Hərrac sayı:</span>
                <span class="col-12 col-lg-4" id="auctionCountImage">@Model.AuctionCount</span>
            </span>
        </div>
        <div class="topbottom col-lg-12 col-12">
            <span class="col-lg-8 col-8 topelement">
                <span class="col-lg-2 col-12">VIN:</span>
                <span class="col-lg-10 col-11" id="vinCodeImage">@Model.Vin</span>
                <input asp-for="Vin" style="display: none" class="d-none" />
            </span>
            <span class="col-lg-4 col-4 topelement">
                <span class="col-12 col-lg-8">Şəkil sayı:</span>
                <span class="col-12 col-lg-4" id="photoCountImage">@Model.ImageCount</span>
            </span>
        </div>
    </div>

    <div class="col-lg-12 col-12 bottom">
        <div class="col-lg-3 col-3-5">

        </div>
        <button type="submit" disabled>Tezliklə!</button>
    </div>
</form>

Vinyoxla.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
    <meta name="description" content="Sadəcə Vin kodunuzu qeyd edin, və avtomobiliniz haqqda hər bir məlumata sahib olun!">
    <meta name="author" content="Vinyoxla.az">
    <meta name="robots" content="follow, index, max-snippet:-1, max-video-preview:-1, max-image-preview:large, vin kod yoxlamaq,
          vinyoxla, vin yoxla, karfaks, carfax, vini, turbo az, turbo" />

    <meta name="keywords" content="VIN kod, vinkod baki, vinkod yoxlamag, carfax yoxlamaq, carfax yoxla, karfax yoxlamaq,
          karfax yoxla, karfax yoxlamag, karfaks yoxla, karfaks baki, karfaks yoxlamag, karfaks yoxlamaq
          carfax baku, carfax baki, carfax yoxlamag, karfaks, vin yoxlamaq, vin yoxlamag, vinyoxla, autoreport,
          autoreport az, report, report almaq, carfax mashin, turbo.az, turbo az, masin yoxlamaq, masin yoxlamag,
          turbo, tap, tap az, tap.az, mashinal, mashin al BAN kod, VIN kod yoxlamaq, karfax, carfax, vin kod, vin code
          BAN kod yoxlamaq, VIN axtarış, BAN axtarış, VIN tarixçəsi, BAN tarixçəsi, VIN tarixi,
          BAN tarixi, avtomobil tarixçəsi, carfax, autocheck, pulsuz tarixçə hesabatı, autoreport, vini,
          avtomobil tarixçəsi hesabatı, carfax hesabat, autocheck hesabat, avtomobilin xüsusiyyətləri,
          VIN üzrə axtarış, BAN üzrə axtarış, BAN ilə axtarış, copart auksion hesabatı, vin kod hesabat,
          copart hesabatı, ucuz carfax, tarixce yoxlamag, carfax mobil, iaai baku,
          iaai baki, copart baku, copart azerbaycan, copart mashin, iaai mashin almaq">

    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7753012657572384"
            crossorigin="anonymous"></script>

    <meta property="og:type" content="website">
    <meta property="og:title" content="Ən ucuz yol ilə CarFax reportunuzu əldə edin! | Avtomobilləri VinKod ilə yoxlamaq artıq çox rahatdır!">
    <meta property="og:description" content="Sadəcə Vin kodunuzu qeyd edin, və avtomobiliniz haqqda hər bir məlumata sahib olun!">
    <meta property="og:image" content="https://vinyoxla.az/assets/images/fotkaOG-min.jpg">
    <meta property="og:url" content="https://vinyoxla.az">

    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="Ən ucuz yol ilə CarFax reportunuzu əldə edin! | Avtomobilləri VinKod ilə yoxlamaq artıq çox rahatdır!">
    <meta name="twitter:description" content="Sadəcə Vin kodunuzu qeyd edin, və avtomobiliniz haqqda hər bir məlumata sahib olun!">

    <meta name="google-site-verification" content="T0ET5Ldc2-H_HHgacXTDiWSL5uInvNjvjC_M4snlGs8" />

    <link rel="stylesheet" href="~/assets/styles/plugins/bootstrap-5.0.2-dist/css/bootstrap.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
          integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="icon" href="~/assets/images/icons8-car-96.png">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"
          integrity="sha512-vKMx8UnXk60zUwyUnUPM3HbQo8QfmNx7+ltw8Pm5zLusl1XIfwcxo8DbWCqMGKaWeNxWA8yrx5v3SaVpMvR3CA=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" type="text/css" href="~/assets/slick-1.8.1/slick/slick.css" />

    <link rel="stylesheet" type="text/css" href="~/assets/slick-1.8.1/slick/slick-theme.css" />

    <link rel="stylesheet" href="~/assets/styles/style.css" asp-append-version="true">
    <!-- built by Vasif Aliyev  -->
    <!-- https://vasifaliyev.com -->
    <title>Avtomobillərin VİN kodunun yoxlanışı və CarFax reportunun əldə edilməsi</title>

    <script type="application/ld+json">
        @Html.Raw("{\"@context\":\"http://schema.org\",\"@type\":\"Organization\",\"name\":\"Vinyoxla\",\"url\":\"https://vinyoxla.az\",\"logo\":\"https://vinyoxla.az/assets/images/fotkaOG-min.jpg\"}")
    </script>

    <script async src="https://www.googletagmanager.com/gtag/js?id=G-TL42BN5SCF">
    </script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'G-TL42BN5SCF');
    </script>
</head>

<body class="body">

    <div class="preloaderdiv col-lg-12 col-12 ">
        <div class="preloader"></div>
    </div>

    <header id="header">
        <div class="container">
            <div class="row all">
                <div class="col-lg-1-8 col-3-5">
                    <a asp-controller="Home" asp-action="Index">
                        <img class="img-fluid" src="~/assets/images/logowhite-min.png" alt="">
                    </a>
                </div>
                <div class="col-lg-4 col-8-5">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a asp-controller="Account" asp-action="Logout" class="">
                            Çıxış
                        </a>
                        <a asp-controller="Account" asp-action="Profile" class="">
                            Hesabım
                        </a>
                    }
                    else
                    {
                        <a asp-controller="Account" asp-action="Login" class="">
                            Daxil ol
                        </a>
                    }
                    <a asp-controller="About" asp-action="Index" class="">
                        Haqqımızda
                    </a>
                </div>
            </div>
        </div>
    </header>

    @RenderBody()

    <div class="keys" style="opacity: 0; height: 1px; overflow-y: scroll;">
        VIN kod, vinkod baki, vinkod yoxlamag,
        carfax baku, carfax baki, carfax yoxlamag, karfaks, vin yoxlamaq, vin yoxlamag, vinyoxla, autoreport,
        autoreport az, report, report almaq, carfax mashin, turbo.az, turbo az, masin yoxlamaq, masin yoxlamag,
        turbo, tap, tap az, tap.az, mashinal, mashin al BAN kod, VIN kod yoxlamaq, karfax, carfax, vin kod, vin code
        BAN kod yoxlamaq, VIN axtarış, BAN axtarış, VIN tarixçəsi, BAN tarixçəsi, VIN tarixi,
        BAN tarixi, avtomobil tarixçəsi, carfax, autocheck, pulsuz tarixçə hesabatı, autoreport, vini,
        avtomobil tarixçəsi hesabatı, carfax hesabat, autocheck hesabat, VIN texniki xüsusiyyətləri,
        BAN texniki xüsusiyyətləri, BAN xüsusiyyətləri, VIN xüsusiyyətləri, VIN dəqiqləşdirilməsi,
        BAN dəqiqləşdirilməsi, VIN avadanlıq, VIN avadanlıqları, avadanlıq axtar, avtomobilin xüsusiyyətləri,
        VIN üzrə axtarış, BAN üzrə axtarış, BAN ilə axtarış, copart auksion hesabatı, vin kod hesabat,
        copart hesabatı, ucuz carfax, ucuz autocheck, yaponiya avtomobil hesabatı, honda, yoxla,
        yaponiya avtomobilini yoxlamaq, yapon avtomobil tarixi, yaponiyadan avtomobil tarixi, tarixce yoxlamag,
        carfax api, autocheck api, copart api, carfax mobil, autocheck mobil, copart mobil, iaai baku,
        iaai baki, copart baku, copart azerbaycan, copart mashin, iaai mashin almaq, auksion, akcion, baku aukcion,
        mashin auction, mashin auksion, mashin almaq, prius, toyota, bmw, mercedes, corolla, camry, insight, insayt, cruze,
        chevrolet, shevrole, curuz, trend azerbaycan, azerbaycan, pirus, pirius, prius, 528, 535, bmw 528, toyota pirus,
        toyota prius, toyota camry, toyota corolla
    </div>

    <footer id="footer">
        <div class=" all">
            <div class="col-lg-0-8 col-1-5 left">
                <a target="_blank" href="https://www.facebook.com/garantauto.az" class="fblink">
                    <i class="fa-brands fa-facebook"></i>
                </a>
                <a target="_blank" href="https://www.instagram.com/garantauto.az/" class="instalink">
                    <i class="fa-brands fa-instagram"></i>
                </a>
            </div>

            <p class="col-lg-9 col-8 middle">
                vinyoxla.az <a target="_blank" href="https://garantauto.az/">&nbsp;"Garant Auto"</a> MMC-nin
                məhsuludur.
            </p>

            <div class="col-lg-0-8 col-2 right">
                <img class="col-lg-5 col-5 img-fluid" src="~/assets/images/visa-card-logo-9.png" alt="">
                <img class="col-lg-5 col-5 img-fluid"
                     src="~/assets/images/mastercard-logo-png-transparent-svg-vector-bie-supply-1.png" alt="">
            </div>
        </div>
        <p class="creator">
            Developed by <a target="_blank" href="https://vasifaliyev.com">Vasif Aliyev</a>
        </p>
    </footer>


    <!-- JQUERY  -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- Bootstrap -->
    <script src="~/assets/styles/plugins/bootstrap-5.0.2-dist/js/bootstrap.bundle.min.js"></script>
    <!-- Toastr -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"
            integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- Slick -->
    <script src="~/assets/slick-1.8.1/slick/slick.min.js"></script>
    <!-- axios -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.2.1/axios.min.js"
            integrity="sha512-zJYu9ICC+mWF3+dJ4QC34N9RA0OVS1XtPbnf6oXlvGrLGNB8egsEzu/5wgG90I61hOOKvcywoLzwNmPqGAdATA=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- My JS -->
    <script src="~/assets/scripts/main.js" asp-append-version="true"></script>
</body>

</html>

Vinyoxla.MVC/Views/Shared/_PurchaseForm.cshtml
@model OrderVM

<form method="post" enctype="multipart/form-data" asp-controller="Purchase" asp-action="Purchase" id="purchaseForm" class="col-lg-6 col-12">

    <input style="display: none" class="d-none" asp-for="Vin" />

    <div class="col-lg-12 col-12 buttonandtelkeeper">
        <div class="inputkeeper @(User.Identity.IsAuthenticated ? "d-none" : "col-lg-5-8") col-12">
            <span class=" kodstrani">+994</span>
            <input inputmode="numeric" numeric autocomplete="off" asp-for="PhoneNumber"
                   placeholder="50 500 50 50" type="text" required maxlength="9" minlength="9"
                   class="phonenumber col-lg-9 col-9" id="phonenumber">
        </div>
        <button type="submit" id="purchaseformbutton" class="btn @(User.Identity.IsAuthenticated ? "col-lg-12" : "col-lg-6") col-12">Almaq</button>
    </div>
</form>

Vinyoxla.MVC/Views/Shared/_ResultsContainerPartial.cshtml
@model HomeVM

<div class="col-lg-5-8 col-12 carfaxContainer resultContainer" id="carfaxContainer">
    @await Html.PartialAsync("_CarfaxResultPartial", Model.Carfax)
</div>

<div class="col-lg-5-8 col-12 photosApiResult resultContainer" id="photosApiResult">
    @await Html.PartialAsync("_ImageResultPartial", Model.ImageVM)
</div>

<div class="col-lg-5-8 col-12 reklam">
    <a target="_blank" href="https://garantauto.az/" class="reklamhref">
        <img src="~/assets/images/Banner-1-min.jpg" alt="" class="img-fluid">
    </a>
</div>

<div class="col-lg-5-8 col-12 reklam">
    <a target="_blank" href="https://rusum.az/" class="reklamhref">
        <img src="~/assets/images/rusum-banner-min.jpg" alt="" class="img-fluid">
    </a>
</div>